export default {
    "questions": {
        "What is the area of Madagascar, in square angstroms?": 32,
        "How tall, in feet, is the 22nd tallest building in the world?": 3,
        "What is the mass of Mars in iPhone 5s?": 25,
        "How many Apps have been downloaded from Apple's iTunes Store?": 10,
        "How many different sets of 5 can you pick from a group of 50?": 6,
        "In 2004, how many people worldwide died in motor vehicle accidents?": 6,
        "How many seconds has it been since Thomas Jefferson was born?": 10,
        "How many stories tall is the tallest human ever to live?": 0,
        "How many atoms are in your body?": 28,
        "How many chicken wing segments were consumed during the 2013 Super Bowl?": 9,
        "How many bytes of digital information does humanity produce each day?": 18,
        "What was the estimated size, in bytes, of the library of Congress in 1949?": 10,
        "What is the population of the world's 70th most populous nation?": 7,
        "United Airlines is the largest airline in the world. How many planes comprise their fleet?": 3,
        "What is the average February high temperature in Washington DC, in °D?": 2,
        "The My Lai Massacre occurred on this date in 1968. According to the US army, how many people were killed?": 2,
        "How many automobiles had General Motors produced as of this date in 1968?": 8,
        "What fraction of earth's water supply is contained within living beings (all forms of life)?": -4,
        "How many different types of proteins are in the human body?": 5,
        "How many different amino acids are?": 1,
        "How many hairs are on the average human head?": 5,
        "How many ml of saliva does a human produce in a lifetime? ": 7,
        "How many red blood cells are in one human body?": 13,
        "How many toothpicks can be made from a cord of wood?": 7,
        "How many seconds does it take a dog to locate the direction of a sound?": -3,
        "How many taste buds are on a human tongue?": 4,
        "The diameter of a DNA molecule in inches.": -4,
        "How many base pairs are in one nucleus of one cell?": 10,
        "How many diapers are thrown out in the U.S. each year?": 10,
        "How many years is the ½ life of Carbon-14?": 4,
        "How many years does it take for Styrofoam to biodegrade?": 4,
        "What is the amount of energy used in kWh for the average search query on Google?": -4,
        "How many gallons of gasoline are burned each day?": 9,
        "How many active volcanoes are on the surface of the earth?": 3,
        "What is the age of the Earth in seconds?": 17,
        "The number of Earths that would fit inside of the sun?": 6,
        "The approximate weight of a 150lb person if they were able to stand on the surface of the sun?": 3,
        "The number of years ago that Pangaea existed as a supercontinent?": 8,
        "The speed of the Earth in miles per hour that it travels through space?": 5,
        "How many pounds of food are eaten by one human in one lifetime?": 5,
        "The mass of the earth in tons?": 22,
        "How many ways can you make change for a dollar?": 2,
        "How many dimples are on a U.S. regulation golf ball?": 2,
        "How many times will you blink this year?": 7,
        "What is the speed of a sneeze in cm/s?": 5,
        "How many kilometers long is the Great Barrier Reef?": 3,
        "How many tons one cubic cm of a neutron star would be?": 8,
        "The speed of light in m/s.": 8,
        "Number of galaxies in the universe.": 11,
        "Pounds of skin shed by a person in his or her lifetime.": 2,
        "How many seconds would it take a heavy object to sink into the deepest part of the ocean?": 3,
        "The number of neutrinos that are produced from the sun that pass through your body while you read this sentence.": 15,
        "Number of miles the universe expands in one hour.": 9,
        "The number of stars in our solar system.": 0,
        "Average number of seconds a Koala spends sleeping each day": 5,
        "The number of atoms in one mole.": 24,
        "How many feet above sea level is the highest point of Florida?": 2,
        "How many square miles are the 48 contiguous U.S. states?": 6,
        "How many people in the U.S. are unemployed?": 7,
        "What is the population density (people per square mile) in the country of Mali?": 1,
        "How many miles are between Stockholm and Paris?": 3,
        "How many toothpicks are required to cover a baseball diamond if the tooth picks are lying flat and sideby-side?": 7,
        "What is the maximum weight, in tons, of a Giant Sequoia tree?": 3,
        "How many 7-11 stores are there in Virginia?": 3,
        "How many babies are born each year in the world?": 5,
        "How many stone blocks were used to build the pyramid at Giza?": 6,
        "How many milk cows are in the U.S.?": 7,
        "How many steps does the average American walk during their lifetime?": 8,
        "How many dollar bills would need to be stacked to reach the moon?": 12,
        "How many tennis balls does it take to cover the playing surface of a tennis court (including the doubles alley)?": 6,
        "What is the maximum speed of the garden snail in mph?": -2,
        "How many metric tons of fish are caught in the country of Jordan each year?": 3,
        "How many decimeters deep is the Marianas Trench?": 5,
        "How many liters of water are there is an Olympic-sized swimming pool?": 6,
        "How many federal, state, and local governmental employees are there in the U.S.? ": 7,
        "How many popular votes separated Obama and McCain during the 2008 presidential election?": 7,
        "How many car miles were avoided in 2010 by buses that took kids to school?": 11,
        "What is the volume of the average adult in dekaliters?": 1,
        "How many troy ounces of gold were produced last year?": 5,
        "How many earths are needed to have the equivalent weight of one Sun?": 5,
        "How many gas stations are there in the U.S.?": 5,
        "How many golf balls will fit in a 747?": 7,
        "How many cups of coffee does Starbucks sell each year?": 9,
        "How many watts of solar power are/were produced in the U.S. today at noon?": 10,
        "How many stars are in the Milky Way Galaxy?": 11,
        "How many kilometers does light travel between two consecutive visits of Haley's comet?": 15,
        "How many electrons flow through a 3 Amp wire each minute?": 21,
        "How many milligrams does the earth weigh?": 31,
        "What percent of the world's water is in rivers?": -4,
        "How many farms are there in Virginia?": 4,
        "How many miles of railroad are operational in the U.S.?": 5,
        "How many different species of spiders and scorpions are there in the world?": 5,
        "How many joules does the sun emit per second?": 26,
        "What is the frequency of an FM radio signal, in cycles per second?": 8,
        "What is the wavelength of an FM radio signal, in meters?": 0,
        "Forrest Gump ran from the coast of Maine to Los Angeles. How many steps did he take?": 7,
        "How many stacked 2 x 4 LEGO blocks would it take to reach the height of the Empire state Building?": 4,
        "Now how many standard 2x4 LEGO blocks would I need  to make an actual-size replica of the Empire state Building?": 11,
        "How long, in hours, does it take for a beam of light to traverse the continental U.S.?": -6,
        "How old is the Earth, in seconds?": 17,
        "How many nanometers span the entire range of visible light?": 2,
        "How many nanometers are in a megaparsec?": 31,
        "How many milliliters of blood does the American Red Cross collect in the US in a given year?": 10,
        "How many atoms of lead would make a ton of lead?": 27,
        "How many paperclips would I need to make a chain long enough to reach the moon from the Earth?": 10,
        "How many drops of water are in a full bathtub?": 7,
        "How many bones are in the human body?": 2,
        "How many miles of highway make up the US Interstate Highway system?": 4,
        "Estimate the mass in grams of all the fans at a home Phillies game.": 9,
        "How many days would it take you to count to a million?": 1,
        "How many electrons pass through a 100 watt light bulb in a minute? ": 22,
        "How many dollars would a quadrillionaire have?": 15,
        "How many leaves are on a mature, healthy oak tree?": 5,
        "Assuming each leaf gets full sunlight, how much energy (watts) does it get from the sun in one year? ": 8,
        "I bought a 2 terabyte hard drive. How many bytes of information can it hold?": 12,
        "How many light-years is the distance from the Earth to the Sun?": -5,
        "Two people stand on opposite sides of the Earth. What is the gravitational force between them?": -21,
        "How many cases of food-borne botulism occur in the United States annually?": 1,
        "What is the lethal dose of botulism toxin, in grams, for a 150 pound human?": -7,
        "How many different species of fish did the Census of Marine Life discover in the past year?": 2,
        "How many Christmas trees were produced in Ohio last year?": 6,
        "If one were to move closer and closer to a carbon atom, at what distance, in meters, would the nucleus appear?": -12,
        "How much voltage can a large electric eel produce?": 3,
        "What is the distance, in meters, of a satellite in geosynchronous orbit about the Earth?": 7,
        "What is the distance from the Sun to Pluto measured in meters?": 13,
        "According to the U.S. Bureau of the Census, what was the resident population of the United States on 1/1/2005?": 8,
        "What is the average diameter of a human hair in millimeters?": -1,
        "How many square kilometers of Lake Erie are solely under the jurisdiction of the USA?": 4,
        "What is the annual consumption of ice cream, in pounds, for the State of Ohio?": 8,
        "What is the average rate of continental drift, in meters per day, along the Mid-Atlantic Ridge?": -4,
        "Determine the density of oxygen in the air of this room at 25°C and 760 torr in g/L.": 0,
        "How many total kg of carbon monoxide were produced in 2001 in the US as Air Pollutant Emissions?": 11,
        "What fraction of a cubic meter is a milliliter?": -6,
        "What is the length, in meters, of the shortest form of an X-ray wavelength?": -11,
        "How many breaths does the average U.S. adult take in a lifetime?": 10,
        "How many seconds were cell phones used in 2003 by the U.S. population?": 10,
        "How many organic and inorganic substances were registered with the Chemical Abstracts service as of Jan. 1, 2005?": 7,
        "What is the number of somatic cells in a 49 day old, normally developing fetus?": 2,
        "How many genes are currently considered part of the human genome?": 4,
        "What is the mass, in grams, of all electrons within a single copper atom?": -26,
        "How many microseconds would it take to count to a trillion, if you count 100 numbers in 1 minute?": 18,
        "How many gallons of milk is produced in the United States each year?": 10,
        "How many hours of sleep does an average person get in a life time in the U.S.?": 5,
        "What is the world demand for oil in gallons each year?": 9,
        "How many millimeters are there in one (1) degree of latitude at 40 degrees North latitude?": 8,
        "125! = ": 209,
        "How much would $1,000 be worth if it was compounded annually at an interest of 8% for 50 years?": 4,
        "How many people in the U.S. have the five most common last names in the U.S.?": 7,
        "What is the maximum depth in meters of the Gulf of Mexico?": 3,
        "If the national debt were represented with a stack of $1 bills, how far would the stack reach in miles?": 6,
        "18.7 billion texts are sent each day around the world. How many of these texts are sent each day from the U.S.?": 9,
        "How many milliliters per year of bottled water are purchased/drank per person in the U.S.?": 5,
        "How many golf balls can fit in a school bus?": 5,
        "What is the total length of all hairs shed by a cat in a month in cm?": 6,
        "What is the total number of millimeters that runners run who cross a finish line in a marathon?": 7,
        "How many revolutions does a car tire make in an hour traveling 100 kilometers per hour?": 5,
        "How many platelets are in each liter of human blood?": 11,
        "How many red blood cells does the U.S. Congress have?": 16,
        "How many paper bags are made from 14 million trees?": 10,
        "How many lawyers are there in the United States?": 6,
        "How much carbon dioxide in grams is emitted annually into the atmosphere by all U.S. power plants?": 15,
        "How many milliliters of water are in the Great Lakes": 19,
        "What are odds of having a deer-vehicle collision in North Carolina in the next 12 months?": -3,
        "How many grams of feces is produced annually by hogs in North Carolina?": 13,
        "How many texts are sent every hour of every day worldwide, not including app-to-app messaging?": 9,
        "How many school buses to equal the weight of the sun ?": 26,
        "What is the acceleration caused by Earth's gravity divided by free fall acceleration of the Sun?": -2,
        "How many red blood cells are needed to blanket the surface area of an M&M?": 7,
        "How many playing cards are needed toblanket the surface area of a doubles tennis court?": 4,
        "What is 137 to the power of 56?": 119,
        "How many electrons are there in our Sun?": 57,
        "How many toothpicks could be made from a telephone pole?": 6,
        "How many new passenger cars are sold each year in the USA": 6,
        "How many aluminum drink cans are used each year in the world?": 11,
        "How many new telephone numbers became available when the three-digit area code system was installed?": 12,
        "During the time interval of a blink, how many km has light travelled in a vacuum?": 5,
        "What is the volume of the Moon in cubic meters?": 19,
        "How many hours elapse from one full moon to the next?": 3,
        "How far, in km, does light travel during the time it takes between full moons?": 12,
        "Relative to the sun, what is the Earth's orbital velocity in miles per hour?": 5,
        "How many kilometers would theEarth have travelled during the time it takes between full moons?": 8,
        "How many SO bacteria would be able to be packed into a ping pong ball?": 13,
        "How many airline passengers are in the air over the United States right now?": 6,
        "What is the kinetic energy stored in continental drift?": 4,
        "How many babies are born in New Haven on an average day?": 1,
        "How many trees are there in Connecticut?": 7,
        "How long a line can an average pencil make in kilometers?": 2,
        "How many piano tuners are there in Chicago?": 2,
        "What is pi to the power of 9?": 4,
        "How many pounds of rice were consumed by people living in the U.S. last year?": 10,
        "How many board game dice does it take to equal the mass of the average human?": 4,
        "How much trash (in pounds) does the average family produce in a year?": 3,
        "What volume of air (in Liters) do you breathe in one day?": 3,
        "How many pennies would it take to make a stack the height of the Empire State Building?": 5,
        "How many centimeters are in 40,000 miles?": 10,
        "How many bird species are there in North America?": 3,
        "How many molecules of ATP are used in an average human in one day?": 26,
        "How many fish are there, on average, per meter cubed of water in the Earth's ocean?": -6,
        "What is the worldwide coffee bean production in picograms?": 25,
        "Norway is the 118th most populous country in the world. What is the population of Norway?": 7,
        "How many different ways are there to arrange 8 objects in a circle?": 4,
        "How many times more massive is the Sun than the Moon?": 7,
        "How many carbon atoms would it take in order to create a single-file line of atoms around the Earth?": 17,
        "What is the force required to break a covalent bond, in Newtons?": -9,
        "How much mass, in kg, is the Sun losing every second?": 9,
        "How many grams of cheese does Wisconsin produce every day?": 9,
        "As of 2017, how many minutes of movie has Steven Spielberg directed?": 3,
        "Surface area of an iPhone in hectares": -6,
        "Mass of a mole(unit) of moles(animal) in ounces": 24,
        "How mnay credit cards would fit in the stratosphere": 25,
        "A sample of pure iridium weighs as much as a bread loaf. How many atom of iridium are in this sample?": 24,
        "Electron diameter in light years": -32,
        "How many individual fries does McDonald's sell yearly": 12,
        "How many cells are in the typical human body?": 13
    }
}